declare namespace NodeJS {
  interface ProcessEnv {
    DB_USER: string;
    DB_PASS: string;
    NEXT_PUBLIC_CLOUDINARY_URL: string;
    NEXT_PUBLIC_CLOUDINARY_NAME: string;
    NEXT_PUBLIC_CLOUDINARY_PRESET: string;
    NEXT_PUBLIC_CLOUDINARY_FEATURED_IMAGE_TRANSFORMATION: string;
    NEXT_PUBLIC_CLOUDINARY_CARD_IMAGE_TRANSFORMATION: string;
    NEXT_PUBLIC_NUM_RECENT_POSTS: number;
  }
}
